version: "3.9"
services:
  redis:
    container_name: loveletter-redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    command: redis-server ./redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/redis:ro
      - ./redis/redis.conf:$PWD/redis/redis.conf 
    
  api:
    container_name: loveletter-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/backend/src/
    # restart: always

  ui:
    container_name: loveletter-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    # restart: always
    volumes:
      - ./frontend/src:/frontend/src/
      - ./frontend/public:/frontend/public/
      - ./frontend/index.html:/frontend/index.html
